### PR TITLE
[DART-1041] - Adding parameterize Kafka offsets configuration via environment variables

### PR DESCRIPTION
**Pull request by yanzv**

### CODE REVIEW

**Comment by yanzv** [comment]
@spilioeve Thanks for merging the PR.  Can you please build a new docker image and push it to the dockerhub.

**Comment by spilioeve** [comment]
Sure, is it okay if I do it later today? I have a few new changes that I
need to include so Sofia can run with the new ontology (after they finalize
the ontology, I will build the image).

**Comment by yanzv** [comment]
Perfect. Thanks!

**Comment by spilioeve** [comment]
Hi Yan,

I am sorry for the delay; the final ontology version was published just an
hour ago. I re-build the docker and pushed it (it should be up in a few
mins). Please lmk if it all looks good; the main difference for Sofia is
the ontology, so you shouldn't have any issues.

Thanks,
Evangelia

**Pull request merged**
